<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BaggageDelivery.Api" />
    <InternalsVisibleTo Include="BaggageDelivery.UnitTests" />
    <InternalsVisibleTo Include="BaggageDelivery.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
    <PackageReference Include="AWSSDK.SecretsManager" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Mjml.Net" />
    <PackageReference Include="Polly" />
    <PackageReference Include="SendGrid" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Twilio" />
  </ItemGroup>

</Project>
