// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaggageDelivery.Core.Models;

public partial class BagDelConfirmationOutbox
{
    public int Id { get; set; }

    public int BookingId { get; set; }

    public int JobId { get; set; }

    public int TenantId { get; set; }

    public string Status { get; set; }

    public int AttemptCount { get; set; }

    public DateTime NextAttemptUtc { get; set; }

    public string LastError { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual BagDelBooking Booking { get; set; }
}