// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaggageDelivery.Core.Models;

public partial class BagDelBooking
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public int TenantId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? ConfirmedAtUtc { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string Suburb { get; set; }

    public string City { get; set; }

    public string PostCode { get; set; }

    public string Country { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public DateTime? TimeSlotStartUtc { get; set; }

    public DateTime? TimeSlotEndUtc { get; set; }

    public string AtlOption { get; set; }

    public string AccessNotes { get; set; }

    public string PhoneOverride { get; set; }

    public DateTime? DespatchSyncedAtUtc { get; set; }

    public string DespatchSyncError { get; set; }

    public virtual ICollection<BagDelConfirmationOutbox> BagDelConfirmationOutboxes { get; set; } = new List<BagDelConfirmationOutbox>();

    public virtual ICollection<BagDelNotificationLog> BagDelNotificationLogs { get; set; } = new List<BagDelNotificationLog>();
}