// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BaggageDelivery.Core.Models;

public partial class BaggageDeliveryContext : DbContext
{
    public BaggageDeliveryContext(DbContextOptions<BaggageDeliveryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BagDelBooking> BagDelBookings { get; set; }

    public virtual DbSet<BagDelConfirmationOutbox> BagDelConfirmationOutboxes { get; set; }

    public virtual DbSet<BagDelNotificationLog> BagDelNotificationLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BagDelBooking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BagDelBo__3214EC07B98AE1DE");

            entity.ToTable("BagDelBooking");

            entity.HasIndex(e => e.JobId, "IX_BagDelBooking_JobId");

            entity.HasIndex(e => e.TenantId, "IX_BagDelBooking_TenantId");

            entity.Property(e => e.AccessNotes).HasMaxLength(500);
            entity.Property(e => e.AddressLine1).HasMaxLength(200);
            entity.Property(e => e.AddressLine2).HasMaxLength(200);
            entity.Property(e => e.AtlOption)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.ConfirmedAtUtc).HasColumnType("datetime");
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreatedAtUtc).HasColumnType("datetime");
            entity.Property(e => e.DespatchSyncedAtUtc).HasColumnType("datetime");
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.PhoneOverride).HasMaxLength(40);
            entity.Property(e => e.PostCode).HasMaxLength(20);
            entity.Property(e => e.Suburb).HasMaxLength(100);
            entity.Property(e => e.TimeSlotEndUtc).HasColumnType("datetime");
            entity.Property(e => e.TimeSlotStartUtc).HasColumnType("datetime");
        });

        modelBuilder.Entity<BagDelConfirmationOutbox>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BagDelCo__3214EC070899C255");

            entity.ToTable("BagDelConfirmationOutbox");

            entity.HasIndex(e => e.Status, "IX_BagDelConfirmationOutbox_Status");

            entity.Property(e => e.AttemptCount).HasAnnotation("Relational:DefaultConstraintName", "DF_BagDelConfirmationOutbox_Attempts");
            entity.Property(e => e.CreatedAtUtc)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BagDelConfirmationOutbox_Created")
                .HasColumnType("datetime");
            entity.Property(e => e.NextAttemptUtc).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Booking).WithMany(p => p.BagDelConfirmationOutboxes)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BagDelConfirmationOutbox_Booking");
        });

        modelBuilder.Entity<BagDelNotificationLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BagDelNo__3214EC07F291F729");

            entity.ToTable("BagDelNotificationLog");

            entity.HasIndex(e => e.Status, "IX_BagDelNotificationLog_Status");

            entity.Property(e => e.AttemptCount).HasAnnotation("Relational:DefaultConstraintName", "DF_BagDelNotificationLog_Attempts");
            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BagDelNotificationLog_Created")
                .HasColumnType("datetime");
            entity.Property(e => e.NextAttemptUtc).HasColumnType("datetime");
            entity.Property(e => e.ProviderMsgId).HasMaxLength(100);
            entity.Property(e => e.Recipient)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAtUtc)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BagDelNotificationLog_Updated")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Booking).WithMany(p => p.BagDelNotificationLogs)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BagDelNotificationLog_Booking");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}