// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BaggageDelivery.Core.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BaggageDelivery.Core.Models
{
    public partial class BaggageDeliveryContext
    {
        private IBaggageDeliveryContextProcedures _procedures;

        public virtual IBaggageDeliveryContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new BaggageDeliveryContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBaggageDeliveryContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class BaggageDeliveryContextProcedures : IBaggageDeliveryContextProcedures
    {
        private readonly BaggageDeliveryContext _context;

        public BaggageDeliveryContextProcedures(BaggageDeliveryContext context)
        {
            _context = context;
        }

        public virtual async Task<List<BagDel_stpAvailableServicesResult>> BagDel_stpAvailableServicesAsync(int? clientID, string size, string fromSuburb, string toSuburb, string weight, int? items, DateTime? dateTime, decimal? kms, int? fromPostCode, int? toPostCode, int? pickup, int? dropoff, int? overSizeItems, int? overWeightItems, bool? privateRes, bool? dangerousGoods, DateTime? truckStartTime, double? truckHours, string ourRef, string clientRefA, string clientRefB, string cubicList, string weightList, int? stockSizeId, decimal? fromLatitude, decimal? fromLongitude, decimal? toLatitude, decimal? toLongitude, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientID",
                    Value = clientID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Size",
                    Size = 10,
                    Value = size ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FromSuburb",
                    Size = 60,
                    Value = fromSuburb ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ToSuburb",
                    Size = 60,
                    Value = toSuburb ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Weight",
                    Size = 200,
                    Value = weight ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Items",
                    Value = items ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DateTime",
                    Value = dateTime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "Kms",
                    Precision = 18,
                    Scale = 2,
                    Value = kms ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "FromPostCode",
                    Value = fromPostCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ToPostCode",
                    Value = toPostCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Pickup",
                    Value = pickup ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Dropoff",
                    Value = dropoff ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OverSizeItems",
                    Value = overSizeItems ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OverWeightItems",
                    Value = overWeightItems ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PrivateRes",
                    Value = privateRes ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "DangerousGoods",
                    Value = dangerousGoods ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "TruckStartTime",
                    Value = truckStartTime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "TruckHours",
                    Value = truckHours ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "OurRef",
                    Size = 40,
                    Value = ourRef ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientRefA",
                    Size = 200,
                    Value = clientRefA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientRefB",
                    Size = 200,
                    Value = clientRefB ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CubicList",
                    Size = 800,
                    Value = cubicList ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "WeightList",
                    Size = 800,
                    Value = weightList ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "StockSizeId",
                    Value = stockSizeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FromLatitude",
                    Precision = 18,
                    Scale = 9,
                    Value = fromLatitude ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "FromLongitude",
                    Precision = 18,
                    Scale = 9,
                    Value = fromLongitude ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "ToLatitude",
                    Precision = 18,
                    Scale = 9,
                    Value = toLatitude ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "ToLongitude",
                    Precision = 18,
                    Scale = 9,
                    Value = toLongitude ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<BagDel_stpAvailableServicesResult>("EXEC @returnValue = [dbo].[BagDel_stpAvailableServices] @ClientID = @ClientID, @Size = @Size, @FromSuburb = @FromSuburb, @ToSuburb = @ToSuburb, @Weight = @Weight, @Items = @Items, @DateTime = @DateTime, @Kms = @Kms, @FromPostCode = @FromPostCode, @ToPostCode = @ToPostCode, @Pickup = @Pickup, @Dropoff = @Dropoff, @OverSizeItems = @OverSizeItems, @OverWeightItems = @OverWeightItems, @PrivateRes = @PrivateRes, @DangerousGoods = @DangerousGoods, @TruckStartTime = @TruckStartTime, @TruckHours = @TruckHours, @OurRef = @OurRef, @ClientRefA = @ClientRefA, @ClientRefB = @ClientRefB, @CubicList = @CubicList, @WeightList = @WeightList, @StockSizeId = @StockSizeId, @FromLatitude = @FromLatitude, @FromLongitude = @FromLongitude, @ToLatitude = @ToLatitude, @ToLongitude = @ToLongitude", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
