// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BaggageDelivery.Core.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BaggageDelivery.Core.Models
{
    public partial interface IBaggageDeliveryContextProcedures
    {
        Task<List<BagDel_stpAvailableServicesResult>> BagDel_stpAvailableServicesAsync(int? clientID, string size, string fromSuburb, string toSuburb, string weight, int? items, DateTime? dateTime, decimal? kms, int? fromPostCode, int? toPostCode, int? pickup, int? dropoff, int? overSizeItems, int? overWeightItems, bool? privateRes, bool? dangerousGoods, DateTime? truckStartTime, double? truckHours, string ourRef, string clientRefA, string clientRefB, string cubicList, string weightList, int? stockSizeId, decimal? fromLatitude, decimal? fromLongitude, decimal? toLatitude, decimal? toLongitude, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
