// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaggageDelivery.Core.Models;

public partial class TblJobSizeName
{
    public string SizeId { get; set; }

    public string SizeName { get; set; }

    public string Name { get; set; }
}